# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: 'curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
  displayName: 'Download the latest Unified Agent'

- script: 'java -jar wss-unified-agent.jar -c wss-unified-agent_pjazure.config -wss.url $WS_WSS_URL -apiKey $WS_APIKEY -projectToken $WS_PROJECT_TOKEN -productToken $WS_PRODUCT_TOKEN'
  displayName: 'Run Unified Agent Scan'
  env:
    WS_APIKEY: $(ORG_API_KEY)
    WS_WSS_URL: $(URL_APP)
    WS_PROJECT_TOKEN: $(TRAININGAZURE_PROJECT_TOKEN)
    WS_PRODUCT_TOKEN: $(MYFAKEAPP_PRODUCT_TOKEN)